name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          always-auth: true
          scope: "@thegetcompany"

      - run: npm ci
      - run: npm run build
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - run: npm version patch
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ASSETS_TOKEN }}
